### ISSUE TITLE
erreur dans corrigé

### ISSUE THREAD

**Issue by flavoiewmvs** [GabrielGamy/INF2120-Demo#1]
public class TaxeDouble  extends  Bien{

```
private final double TAUX_TVQ = 9.975/100;
private final double TAUX_TPS = 5.0/100;    dois avoir 5.0 au lieu 5 
```

**Comment by GabrielGamy** [comment]
Il n'y a aucun problème avec cette déclaration. 5 ou 5.0 pour un nombre
flottant (double ou float) reviens à la même chose.

**Comment by flavoiewmvs** [comment]
autrement il donne 0 a ton taux.

_Fabien Lavoie_

_514-297-4244_
flavoie@wmvs.ca flavoie@wms.ca

2016-05-10 8:40 GMT-04:00 Gabriel Yakpaoro Gamy notifications@github.com:

> Il n'y a aucun problème avec cette déclaration. 5 ou 5.0 pour un nombre
> flottant (double ou float) reviens à la même chose.

**Comment by GabrielGamy** [comment]
Oui c'est vrai. Cela est du au fait qu'on effectue une division. 
Je vais corriger ca.

Merci
